mainSections   = ["post"]
rssFullContent = true

[footer]
    since = 2024

[sidebar]
    emoji    = "ğŸ±"
    subtitle = "è®°å½•ç”Ÿæ´»ï¼Œåˆ†äº«æŠ€æœ¯"

[article]
    [article.license]
        enabled = false

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    enabled = false

[imaging]
    remote = false
